spring:
  application:
    name: car-info-service
  config:
    import: optional:configserver:http://config-server.carmarketplace-dev:8888
  cloud:
    config:
      uri: http://config-server.carmarketplace-dev:8888
      fail-fast: false
      retry:
        maxAttempts: 20